version: 0.2

phases: 
    install:
        runtime-versions:
            java: open-jdk-8
        commands: 
            - echo Entered the install phase ...
    build:
        commands: 
            - echo Entered the build phase ...
            - mvn clean install
artifacts:
    files:
        - target/account-example-0.0.1-SNAPSHOT.jar
        - appspec.yml
        - scripts/*
